[package]
name = "flat-practice"
version = "0.1.0"
authors = ["Lev Malets <lev.mxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flat-practice-lib = { path = "lib" }
anyhow = "1.0.32"
