name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache-graphblas
      uses: actions/cache@v2
      with:
        path: |
          build/bin
          build/lib
          build/lib64
          build/home
          build/include
          ~/.cargo
        key: ${{ runner.os }}-cache
    - name: Prepare
      run: rustup install nightly && rustup default nightly
    - name: Build
      run: make
    - name: Run tests
      run: make test
