name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache GraphBLAS
      id: cache-graphblas
      uses: actions/cache@v2
      with:
        path: ~/GraphBLAS
        key: ${{ runner.os }}
    - name: Get GraphBLAS
      if: steps.cache-graphblas.outputs.cache-hit != 'true'
      run: |
        git clone -b stable --single-branch https://github.com/DrTimothyAldenDavis/GraphBLAS ~/GraphBLAS.repo
        cd ~/GraphBLAS.repo
        make
        cmake -DCMAKE_INSTALL_PREFIX=~/GraphBLAS -B build
        make install
    - name: Build
      run: CPATH=~/GraphBLAS/include cargo build --verbose
    - name: Run tests
      run: LD_LIBRARY_PATH=/tmp/testinst/lib LIBRARY_PATH=/tmp/testinst/lib cargo test --verbose
